const challenges = [
  {
    id: 1,
    title: '운동하기',
    category: 'routine',
    type: 'individual',
    period: 14,
    startDate: '2022.11.25',
    reward: '24시간 잠자기',
    pass: 3,
    status: 'ongoing',
    dajimOpen: '',
    dajimContent: '',
  },
  {
    id: 2,
    title: '밥먹기',
    category: 'routine',
    type: 'group',
    period: 30,
    startDate: '2022.11.25',
    reward: '아이패드',
    pass: 4,
    status: 'success',
  },
  {
    id: 3,
    title: '잠자기',
    category: 'routine',
    type: 'individual',
    period: 60,
    startDate: '2022.11.25',
    reward: '맥북 프로',
    pass: 5,
    status: 'ongoing',
  },
  {
    id: 4,
    title: '여행가기',
    category: 'routine',
    type: 'group',
    period: 14,
    startDate: '2022.11.25',
    reward: '애플워치',
    pass: 2,
    status: 'fail',
  },
];

export default challenges;
